Initial addition of 10.11.5 with working unit tests.
MariaDB4j/MariaDB4j pull request #771
Opened 2023-09-15 20:47 UTC by TheKnowles

mysql binaries are modified in code.
win32 has been replaced with winx64 from maria downloads. 
Security unit test has been updated to account for root user changes in 10.4.

2023-09-15 20:49 UTC, TheKnowles commented
This is a smaller, targeted pass of https://github.com/MariaDB4j/MariaDB4j/pull/710 off of main for Java 17 / Spring Boot 3.

10.11.5 is the latest long term supported release from maria.

Related: https://github.com/MariaDB4j/MariaDB4j/issues/344 https://github.com/MariaDB4j/MariaDB4j/issues/699

2023-09-15 20:53 UTC, TheKnowles reviewed
I've left comments on the pain points from the previous PR.

2023-09-15 20:53 UTC, TheKnowles commented on DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-linux64-10.11.5/prepare.xml
> +                <include name="mariadb"/>
I attempted to keep the mysql* names for backwards compatibility, but the abstraction became leaky very quickly.

2023-09-15 20:53 UTC, TheKnowles commented on mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java
> +    protected static final String WINX64 = "winx64";
maria no longer puts out win32 releases, only winx64.

2023-09-15 20:53 UTC, TheKnowles commented on mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java
> +        executables.putIfAbsent(Server, () -> new File(baseDir, "bin/mariadbd" + getExtension()));
If we kept the original mysql names, we would have to modify the installation script and that becomes very brittle very quickly.

2023-09-15 20:53 UTC, TheKnowles commented on mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java
> +            File bin = new File(baseDir, "bin/mariadb-install-db" + getExtension());
Even if we copied over the new script name into the old script name, it will reference the new binaries. Because these were not chmod +x it would fail because it could not find that executable.

Updating the new script with the old names was untenable.

2023-09-15 20:53 UTC, TheKnowles commented on mariaDB4j/pom.xml
> -			<artifactId>mariaDB4j-db-mac64</artifactId>
Per our previous conversation on the last PR, maxOS support has been dropped. I am experimenting with some virtualbox vms to avoid buying a mac machine. But for now, mac is bespoke and not easily fixed on a linux machine.

2023-09-16 11:13 UTC, vorburger commented
@TheKnowles Great to hear back from you - Thank You for re-engaging, after #710.

I will try to have a closer look at this later today or tomorrow!

2023-09-16 11:15 UTC, vorburger commented on DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-linux64-10.11.5/prepare.xml
> +                <include name="mariadb"/>
I'm totally OK with changing from `mysql*` to `mariadb*` at this point!

2023-09-16 11:43 UTC, vorburger commented
@TheKnowles OK, right, now I better understand... so those would break using MariaDB4j with older MariaDB where binaries still used to be named `mysqld` instead of `mariadbd`, right? I'm personally not really fundamentally opposed to this (anymore), but I do wonder what impact this would have on the (many) other users of this project...

It IS a "breaking" change (for MariaDB4j). At the very least,  this probably justifies changing the version from `3.0.x` to `3.1.x`... (@TheKnowles not asking for you to do that in this PR; I would do it.)

Does anyone watch this repo and is reading along here and would have any opinion about this? Does e.g. anyone still use a [current MariaDB4j v3.0.1 release](https://github.com/MariaDB4j/MariaDB4j/issues/696) but overrides the POM dependency to an OLDER MariaDB than the 10.2.11 which MariaDB4j v3.0.1 comes with? Or use a custom binary artefact built in-house? Or does everyone "just want it to work out of the box" and is fine with, even very happy about and glad for, a future new MariaDB4j release to just depend on latest MariaDB 10.11.5 and not bothered by not able to override the binaries to older versions? Then I'm happy to merge this...

@mosesn @mrdziuban do you have any views pro/con about this PR? Happy to see it? Breaking anything for you internally?

2023-09-16 12:02 UTC, vorburger commented on mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBConfigurationBuilder.java
> +    protected static final String WINX64 = "winx64";
OK, makes sense; that shouldn't be a problem.

2023-09-16 12:09 UTC, vorburger commented on DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-linux64-10.11.5/pom.xml
> +    <version>10.11.5</version>
@TheKnowles this currently produces a `mariaDB4j-db-linux64-10.11.5.jar` with a size of 135 MB / 141526894 bytes. Compared to https://repo1.maven.org/maven2/ch/vorburger/mariaDB4j/mariaDB4j-db-linux64/10.2.11/ at 56792458 bytes, that's ~3x times as big... I did not have a closer look at why, but are there perhaps things included in this JAR which you could filter out here to trim its size a bit?

2023-09-16 12:19 UTC, vorburger commented on mariaDB4j/pom.xml
> -			<artifactId>mariaDB4j-db-mac64</artifactId>
Yeah, I'm fine with this; given even this old Mac x86 `10.2.11` increasingly doesn't work for new Mac users on M1/M2/M3 ARM CPUs anymore anyway, see #497 and https://github.com/MariaDB4j/MariaDB4j#how-using-existing-native-mariadb-binaries. The real solution is probably #296 anyway... maybe I'll play with that one of these days!

2023-09-16 12:27 UTC, vorburger requested changes

2023-09-16 12:27 UTC, vorburger commented on mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java
> +        db.run("SET PASSWORD FOR 'root'@'localhost' = PASSWORD('');", System.getProperty("user.name"), "");
@TheKnowles Oh, interesting. Because this test is also the "Tutorial" [linked prominently from the READ](https://github.com/MariaDB4j/MariaDB4j#how-java), in a sense this promotes doing something "insecure".  I wonder if there is a better solution for this.. What is the `System.getProperty("user.name")` used for here? How does one typically do this in real applications? Should the test perhaps insert a dedicated test user? Or set the root user to a random password, which is used when connecting? Could this entire TutorialTest just not use the (DB, not OS) root user at all? Perhaps improving this is worth a separate smaller PR, as a pre-requisite for this?

2023-09-16 13:05 UTC, vorburger commented on mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java
> +        db.run("SET PASSWORD FOR 'root'@'localhost' = PASSWORD('');", System.getProperty("user.name"), "");
@TheKnowles Please ignore... I have played a bit with this myself, and will slightly improve it in #772. FYI @kaismh and @azell from back in #17 and #83. With that, resolving this for this PR.

2023-09-16 13:20 UTC, vorburger commented on DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-linux64-10.11.5/pom.xml
> +    <version>10.11.5</version>
I have had a closer look at this myself now, and the main reason is that the Linux `bin/mariadbd` is indeed ~297 MB in 10.2.11 instead of the `bin/mysqld` 118 MB in 10.2.11. In that case, so be it! Resolving this.

2023-09-16 13:23 UTC, vorburger approved these changes
I'm OK to merge this as-is. 

I just need to separately push the binaries to Maven central, then this will build, and I'll merge it.

2023-09-16 14:42 UTC, vorburger commented
> It IS a "breaking" change (for MariaDB4j). At the very least, this probably justifies changing the version from 3.0.x to 3.1.x... (@TheKnowles not asking for you to do that in this PR; I would do it.)

I think this makes sense, so what I'll do is release a 3.0.2 (without this), then bump to `3.1.0-SNAPSHOT` and merge this (I'll hold releasing it, for now).

> I just need to separately push the binaries to Maven central, then this will build

Done, and it's green on Linux, but CI fails on Windows... I don't have a Windows machine. @TheKnowles have you tested this locally on Windows? Do you want to have a closer look and see what that `ERROR: Can't write to mysqld's stdin` CI failure on Windows is about? @mosesn do you or your colleagues use Windows and want to contribute to debug this?

2023-09-16 15:02 UTC, vorburger commented
> but CI fails on Windows... I

The reason seems to be this:

```
[main] INFO ch.vorburger.mariadb4j.Util - Unpacked 73 files from classpath*:ch/vorburger/mariadb4j/mariadb-10.11.5/winx64/** to C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base
[main] INFO ch.vorburger.mariadb4j.DB - Installing a new embedded database to: C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base
[main] INFO ch.vorburger.exec.ManagedProcess - Starting Program [C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base\bin\mariadb-install-db.exe, --datadir=C:\Users\runneradmin\AppData\Local\Temp\MariaDB4j\data\54232] (in working directory C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base)
[main] INFO ch.vorburger.exec.ManagedProcess - Thread is now going to wait for this process to terminate itself: Program [C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base\bin\mariadb-install-db.exe, --datadir=C:\Users\runneradmin\AppData\Local\Temp\MariaDB4j\data\54232] (in working directory C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base)
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: Running bootstrap
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: '"C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe"' is not recognized as an internal or external command,
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: operable program or batch file.
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: Creating my.ini file
[Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: FATAL ERROR: database creation failed
[Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: ERROR: Can't write to mysqld's stdin
```

So for some reason, even though it's mostly changed from `mysql*` to `mariadb` something, in the core MariaDB Windows binaries, not this MariaDB4j wrapper project, still calls a `mysqld.exe`? Or did we package it wrong - something missing/wrong in the `mariaDB4j-db-winx64-10.11.5/prepare.xml` in this PR? @TheKnowles do you want to further investigate this? Thank You!

2023-09-17 13:59 UTC, TheKnowles commented
> > but CI fails on Windows... I
> 
> The reason seems to be this:
> 
> ```
> [main] INFO ch.vorburger.mariadb4j.Util - Unpacked 73 files from classpath*:ch/vorburger/mariadb4j/mariadb-10.11.5/winx64/** to C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base
> [main] INFO ch.vorburger.mariadb4j.DB - Installing a new embedded database to: C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base
> [main] INFO ch.vorburger.exec.ManagedProcess - Starting Program [C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base\bin\mariadb-install-db.exe, --datadir=C:\Users\runneradmin\AppData\Local\Temp\MariaDB4j\data\54232] (in working directory C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base)
> [main] INFO ch.vorburger.exec.ManagedProcess - Thread is now going to wait for this process to terminate itself: Program [C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base\bin\mariadb-install-db.exe, --datadir=C:\Users\runneradmin\AppData\Local\Temp\MariaDB4j\data\54232] (in working directory C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base)
> [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: Running bootstrap
> [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: '"C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe"' is not recognized as an internal or external command,
> [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: operable program or batch file.
> [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: Creating my.ini file
> [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: FATAL ERROR: database creation failed
> [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: ERROR: Can't write to mysqld's stdin
> ```
> 
> So for some reason, even though it's mostly changed from `mysql*` to `mariadb` something, in the core MariaDB Windows binaries, not this MariaDB4j wrapper project, still calls a `mysqld.exe`? Or did we package it wrong - something missing/wrong in the `mariaDB4j-db-winx64-10.11.5/prepare.xml` in this PR? @TheKnowles do you want to further investigate this? Thank You!

Yes I will investigate. I only ran the simulated winx64 start.

2023-09-17 18:00 UTC, TheKnowles commented
> > > but CI fails on Windows... I
> > 
> > 
> > The reason seems to be this:
> > ```
> > [main] INFO ch.vorburger.mariadb4j.Util - Unpacked 73 files from classpath*:ch/vorburger/mariadb4j/mariadb-10.11.5/winx64/** to C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base
> > [main] INFO ch.vorburger.mariadb4j.DB - Installing a new embedded database to: C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base
> > [main] INFO ch.vorburger.exec.ManagedProcess - Starting Program [C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base\bin\mariadb-install-db.exe, --datadir=C:\Users\runneradmin\AppData\Local\Temp\MariaDB4j\data\54232] (in working directory C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base)
> > [main] INFO ch.vorburger.exec.ManagedProcess - Thread is now going to wait for this process to terminate itself: Program [C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base\bin\mariadb-install-db.exe, --datadir=C:\Users\runneradmin\AppData\Local\Temp\MariaDB4j\data\54232] (in working directory C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base)
> > [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: Running bootstrap
> > [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: '"C:\Users\RUNNER~1\AppData\Local\Temp\MariaDB4j\base\bin\mysqld.exe"' is not recognized as an internal or external command,
> > [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: operable program or batch file.
> > [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: Creating my.ini file
> > [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: FATAL ERROR: database creation failed
> > [Exec Stream Pumper] INFO ch.vorburger.exec.ManagedProcess - mariadb-install-db.exe: ERROR: Can't write to mysqld's stdin
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So for some reason, even though it's mostly changed from `mysql*` to `mariadb` something, in the core MariaDB Windows binaries, not this MariaDB4j wrapper project, still calls a `mysqld.exe`? Or did we package it wrong - something missing/wrong in the `mariaDB4j-db-winx64-10.11.5/prepare.xml` in this PR? @TheKnowles do you want to further investigate this? Thank You!
> 
> Yes I will investigate. I only ran the simulated winx64 start.

@vorburger Ok, this should be good to go.

There were a handful of issues:

1. We needed to add the mysqld binaries in prepare.xml for Windows. They got called as you previously found.
2. Once those were added, we also needed server.dll and server.lib
3. Windows does not implement the auth introduced in 10.4 where the root user no long has an empty password. So we'll do a check in the unit test to just use the root user instead of the current user.


I have built and run all unit tests passing on Windows 11.

2023-09-17 18:11 UTC, vorburger commented
Cool, Thank You so much! 

I'll re-test this as soon as I can get to it.

2023-09-18 17:45 UTC, vorburger commented
Because I already released https://repo.maven.apache.org/maven2/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5/ (NB the `artifactId` is now new `mariaDB4j-db-winx64`, VS previous `mariaDB4j-db-win32`) on the day before yesterday to Maven Central, while first testing this, but then the scripts here got changed, I wil now have to re-release it; I'll use `10.11.5.1` for that (even though there is of course no such MariaDB binary version).

This time, I'll temporarily "hack" things, and not actually deploy it just yet, but instead `mvn install` (not `deploy`) the artifact  on CI, in a commit which I will drop again before ultimately merging this, to test that this really work. I will be doing this in #772, under which this will get merged (once it works).

2023-09-18 22:12 UTC, vorburger commented
> bump to 3.1.0-SNAPSHOT

done in #779 (@TheKnowles please ignore the merge conflicts that caused here; I will merge the commits from your PR here under the overall PR #772).

> This time, I'll temporarily "hack" things, and not actually deploy it just yet, but instead mvn install (not deploy) the artifact on CI, in a commit which I will drop again before ultimately merging this, to test that this really work. I

see https://github.com/MariaDB4j/MariaDB4j/commit/c6814e64b586e71658abe3842e8484efd1fcfcfa

2023-09-18 22:52 UTC, vorburger commented
> Because I already released https://repo.maven.apache.org/maven2/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5/ (NB the artifactId is now new mariaDB4j-db-winx64, VS previous mariaDB4j-db-win32) on the day before yesterday to Maven Central, while first testing this, but then the scripts here got changed, I wil now have to re-release it; I'll use 10.11.5.1 for that (even though there is of course no such MariaDB binary version).

This does not work... 😭  The `nexus-staging` Maven plugin appears to want to deploy a `10.11.5.1` as both that as well as a `10.11.5`, and (obviously) fails when doing the latter, which aborts the entire deploy, check this out:

```
[INFO] --- install:3.1.0:install (default-install) @ mariaDB4j-db-winx64 ---
[INFO] Installing /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/pom.xml to /home/vorburger/.m2/repository/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1.pom
[INFO] Installing /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/mariaDB4j-db-winx64-10.11.5.1.jar to /home/vorburger/.m2/repository/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1.jar
[INFO] Installing /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/mariaDB4j-db-winx64-10.11.5.1-sources.jar to /home/vorburger/.m2/repository/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1-sources.jar
[INFO] Installing /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/mariaDB4j-db-winx64-10.11.5.1.jar.asc to /home/vorburger/.m2/repository/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1.jar.asc
[INFO] Installing /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/mariaDB4j-db-winx64-10.11.5.1.pom.asc to /home/vorburger/.m2/repository/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1.pom.asc
[INFO] Installing /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/mariaDB4j-db-winx64-10.11.5.1-sources.jar.asc to /home/vorburger/.m2/repository/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1-sources.jar.asc
[INFO]
[INFO] --- nexus-staging:1.6.13:deploy (injected-nexus-deploy) @ mariaDB4j-db-winx64 ---
[INFO] Performing local staging (local stagingDirectory="/home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/nexus-staging/staging")...
[INFO]  + Using server credentials "ossrh" from Maven settings.
[INFO]  * Connected to Nexus at https://oss.sonatype.org:443/, is version 2.15.1-02 and edition "Professional"
[INFO]  * Using staging profile ID "12bb4759cb85ae" (matched by Nexus).
[INFO] Installing /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/mariaDB4j-db-winx64-10.11.5.1.jar to /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/nexus-staging/staging/12bb4759cb85ae/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1.jar
[INFO] Installing /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/pom.xml to /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/nexus-staging/staging/12bb4759cb85ae/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1.pom
[INFO] Installing /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/mariaDB4j-db-winx64-10.11.5.1-sources.jar to /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/nexus-staging/staging/12bb4759cb85ae/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1-sources.jar
[INFO] Installing /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/mariaDB4j-db-winx64-10.11.5.1.jar.asc to /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/nexus-staging/staging/12bb4759cb85ae/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1.jar.asc
[INFO] Installing /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/mariaDB4j-db-winx64-10.11.5.1.pom.asc to /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/nexus-staging/staging/12bb4759cb85ae/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1.pom.asc
[INFO] Installing /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/mariaDB4j-db-winx64-10.11.5.1-sources.jar.asc to /home/vorburger/git/github.com/vorburger/MariaDB4j/DBs/mariaDB4j-db-10.11.5/mariaDB4j-db-winx64-10.11.5/target/nexus-staging/staging/12bb4759cb85ae/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1-sources.jar.asc
[INFO] Performing remote staging...
[INFO]
[INFO]  * Remote staging into staging profile ID "12bb4759cb85ae"
[INFO]  * Created staging repository with ID "chvorburger-1058".
[INFO]  * Staging repository at https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/chvorburger-1058
[INFO]  * Uploading locally staged artifacts to profile ch.vorburger
Uploading to ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/chvorburger-1058/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1.jar.asc
Uploaded to ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/chvorburger-1058/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1.jar.asc (833 B at 1.1 kB/s)
Downloading from ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/chvorburger-1058/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/maven-metadata.xml
Uploading to ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/chvorburger-1058/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/maven-metadata.xml
Uploaded to ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/chvorburger-1058/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/maven-metadata.xml (329 B at 550 B/s)
Uploading to ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/chvorburger-1058/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1-sources.jar.asc
Uploaded to ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/chvorburger-1058/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1-sources.jar.asc (833 B at 2.8 kB/s)
Uploading to ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/chvorburger-1058/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1.pom.asc
Uploaded to ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/chvorburger-1058/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5.1/mariaDB4j-db-winx64-10.11.5.1.pom.asc (833 B at 2.8 kB/s)
Uploading to ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/chvorburger-1058/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5/mariaDB4j-db-winx64-10.11.5.jar
Uploaded to ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/chvorburger-1058/ch/vorburger/mariaDB4j/mariaDB4j-db-winx64/10.11.5/mariaDB4j-db-winx64-10.11.5.jar (7 [...]

2023-09-18 23:31 UTC, vorburger commented
> That's fascinating, I did not realize a point release would not work.

Fascinating is one way to describe the mess that Maven versions are... I just hope (not tested!) that `-fix1` will also work for Gradle, et al! 🤣 

> now released it (the Windows binary only; the Linux one is fine) as that (`10.11.5-fix1`)

And with that, #772 was green, and got merged. With that, I am (finally!) closing this PR, because I squashed the 4 commits from here into 78d17f8a9399c1b4b597c704a597f84ab2ef2ae9, which is now merged to the `main` branch.

2023-09-18 23:31 UTC, closed without merging

2023-09-18 23:45 UTC, TheKnowles commented
Thanks for the review and merge! In retrospect, I should have done a full run on an actual Windows machine. I was surprised how different the maria releases are, I had only done the simulated unit test run from a linux machine.